<a href="https://colab.research.google.com/github/vyshnavi2001/3-assignment/blob/master/array.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Original matrix: ")
print(matrix)
result = np.trace(matrix)
print("Sum of the diagonal elements of a given matrix: ",result)

Original matrix: 
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Sum of the diagonal elements of a given matrix:  15
