<a href="https://colab.research.google.com/github/vyshnavi2001/3-assignment/blob/master/matrix.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
matrix_1 = np.array([[1, 0], [0, 1]])
matrix_2 = np.array([[1, 2], [3, 4]])
print("Orginal matix: ")
print(matrix_1)
print(matrix_2)
print("Outer product of the said two vectors: ")
result = np.outer(matrix_1, matrix_2)
print(result)


Orginal matix: 
[[1 0]
 [0 1]]
[[1 2]
 [3 4]]
Outer product of the said two vectors: 
[[1 2 3 4]
 [0 0 0 0]
 [0 0 0 0]
 [1 2 3 4]]
